title:               The Mast-Head
url:                 https://nicoelayda.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Giulia Brazzale
  url:               labrezza.github.io
  email:             giulia.brazzale@inventati.org

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
